[tool.poetry]
name = "machine-learning"
version = "0.1.0"
description = ""
authors = ["Ravindra Jaju <jaju@msync.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mlx = ">=0.16.1"
torch = ">=2.2.0"
numpy = ">=2.0.1"
matplotlib = ">=3.8.3"
spacy = ">=3.7.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
