// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _err_stackitem {
 *     PyObject *exc_value;
 *     struct _err_stackitem *previous_item;
 * }
 * }
 */
public class _err_stackitem {

    _err_stackitem() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_POINTER.withName("exc_value"),
        Python_h.C_POINTER.withName("previous_item")
    ).withName("_err_stackitem");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout exc_value$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("exc_value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *exc_value
     * }
     */
    public static final AddressLayout exc_value$layout() {
        return exc_value$LAYOUT;
    }

    private static final long exc_value$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *exc_value
     * }
     */
    public static final long exc_value$offset() {
        return exc_value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *exc_value
     * }
     */
    public static MemorySegment exc_value(MemorySegment struct) {
        return struct.get(exc_value$LAYOUT, exc_value$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *exc_value
     * }
     */
    public static void exc_value(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(exc_value$LAYOUT, exc_value$OFFSET, fieldValue);
    }

    private static final AddressLayout previous_item$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("previous_item"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct _err_stackitem *previous_item
     * }
     */
    public static final AddressLayout previous_item$layout() {
        return previous_item$LAYOUT;
    }

    private static final long previous_item$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct _err_stackitem *previous_item
     * }
     */
    public static final long previous_item$offset() {
        return previous_item$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct _err_stackitem *previous_item
     * }
     */
    public static MemorySegment previous_item(MemorySegment struct) {
        return struct.get(previous_item$LAYOUT, previous_item$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct _err_stackitem *previous_item
     * }
     */
    public static void previous_item(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(previous_item$LAYOUT, previous_item$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

