// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _Py_GlobalMonitors {
 *     uint8_t tools[15];
 * }
 * }
 */
public class _Py_GlobalMonitors {

    _Py_GlobalMonitors() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(15, Python_h.C_CHAR).withName("tools")
    ).withName("_Py_GlobalMonitors");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout tools$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("tools"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t tools[15]
     * }
     */
    public static final SequenceLayout tools$layout() {
        return tools$LAYOUT;
    }

    private static final long tools$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t tools[15]
     * }
     */
    public static final long tools$offset() {
        return tools$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t tools[15]
     * }
     */
    public static MemorySegment tools(MemorySegment struct) {
        return struct.asSlice(tools$OFFSET, tools$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t tools[15]
     * }
     */
    public static void tools(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, tools$OFFSET, tools$LAYOUT.byteSize());
    }

    private static long[] tools$DIMS = { 15 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t tools[15]
     * }
     */
    public static long[] tools$dimensions() {
        return tools$DIMS;
    }
    private static final VarHandle tools$ELEM_HANDLE = tools$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t tools[15]
     * }
     */
    public static byte tools(MemorySegment struct, long index0) {
        return (byte)tools$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t tools[15]
     * }
     */
    public static void tools(MemorySegment struct, long index0, byte fieldValue) {
        tools$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

