// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _err_stackitem {
 *     PyObject *exc_value;
 *     struct _err_stackitem *previous_item;
 * } _PyErr_StackItem
 * }
 */
public class _PyErr_StackItem extends _err_stackitem {

    _PyErr_StackItem() {
        // Should not be called directly
    }
}

