// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _stack_chunk {
 *     struct _stack_chunk *previous;
 *     size_t size;
 *     size_t top;
 *     PyObject *data[1];
 * } _PyStackChunk
 * }
 */
public class _PyStackChunk extends _stack_chunk {

    _PyStackChunk() {
        // Should not be called directly
    }
}

