// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _specialization_cache {
 *     PyObject *getitem;
 *     uint32_t getitem_version;
 *     PyObject *init;
 * }
 * }
 */
public class _specialization_cache {

    _specialization_cache() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_POINTER.withName("getitem"),
        Python_h.C_INT.withName("getitem_version"),
        MemoryLayout.paddingLayout(4),
        Python_h.C_POINTER.withName("init")
    ).withName("_specialization_cache");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout getitem$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("getitem"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *getitem
     * }
     */
    public static final AddressLayout getitem$layout() {
        return getitem$LAYOUT;
    }

    private static final long getitem$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *getitem
     * }
     */
    public static final long getitem$offset() {
        return getitem$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *getitem
     * }
     */
    public static MemorySegment getitem(MemorySegment struct) {
        return struct.get(getitem$LAYOUT, getitem$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *getitem
     * }
     */
    public static void getitem(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(getitem$LAYOUT, getitem$OFFSET, fieldValue);
    }

    private static final OfInt getitem_version$LAYOUT = (OfInt)$LAYOUT.select(groupElement("getitem_version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t getitem_version
     * }
     */
    public static final OfInt getitem_version$layout() {
        return getitem_version$LAYOUT;
    }

    private static final long getitem_version$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t getitem_version
     * }
     */
    public static final long getitem_version$offset() {
        return getitem_version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t getitem_version
     * }
     */
    public static int getitem_version(MemorySegment struct) {
        return struct.get(getitem_version$LAYOUT, getitem_version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t getitem_version
     * }
     */
    public static void getitem_version(MemorySegment struct, int fieldValue) {
        struct.set(getitem_version$LAYOUT, getitem_version$OFFSET, fieldValue);
    }

    private static final AddressLayout init$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("init"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *init
     * }
     */
    public static final AddressLayout init$layout() {
        return init$LAYOUT;
    }

    private static final long init$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *init
     * }
     */
    public static final long init$offset() {
        return init$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *init
     * }
     */
    public static MemorySegment init(MemorySegment struct) {
        return struct.get(init$LAYOUT, init$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *init
     * }
     */
    public static void init(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(init$LAYOUT, init$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

