// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     FILE *perf_map;
 *     PyThread_type_lock map_lock;
 * }
 * }
 */
public class PerfMapState {

    PerfMapState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_POINTER.withName("perf_map"),
        Python_h.C_POINTER.withName("map_lock")
    ).withName("$anon$9:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout perf_map$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("perf_map"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * FILE *perf_map
     * }
     */
    public static final AddressLayout perf_map$layout() {
        return perf_map$LAYOUT;
    }

    private static final long perf_map$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * FILE *perf_map
     * }
     */
    public static final long perf_map$offset() {
        return perf_map$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * FILE *perf_map
     * }
     */
    public static MemorySegment perf_map(MemorySegment struct) {
        return struct.get(perf_map$LAYOUT, perf_map$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * FILE *perf_map
     * }
     */
    public static void perf_map(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(perf_map$LAYOUT, perf_map$OFFSET, fieldValue);
    }

    private static final AddressLayout map_lock$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("map_lock"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyThread_type_lock map_lock
     * }
     */
    public static final AddressLayout map_lock$layout() {
        return map_lock$LAYOUT;
    }

    private static final long map_lock$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyThread_type_lock map_lock
     * }
     */
    public static final long map_lock$offset() {
        return map_lock$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyThread_type_lock map_lock
     * }
     */
    public static MemorySegment map_lock(MemorySegment struct) {
        return struct.get(map_lock$LAYOUT, map_lock$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyThread_type_lock map_lock
     * }
     */
    public static void map_lock(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(map_lock$LAYOUT, map_lock$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

