// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _Py_tss_t Py_tss_t
 * }
 */
public class Py_tss_t extends _Py_tss_t {

    Py_tss_t() {
        // Should not be called directly
    }
}

