// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _line_offsets {
 *     int ar_start;
 *     int ar_end;
 *     int ar_line;
 *     struct _opaque opaque;
 * } PyCodeAddressRange
 * }
 */
public class PyCodeAddressRange extends _line_offsets {

    PyCodeAddressRange() {
        // Should not be called directly
    }
}

