// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     PyObject ob_base;
 *     PyTypeObject *d_type;
 *     PyObject *d_name;
 *     PyObject *d_qualname;
 * }
 * }
 */
public class PyDescrObject {

    PyDescrObject() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        _object.layout().withName("ob_base"),
        Python_h.C_POINTER.withName("d_type"),
        Python_h.C_POINTER.withName("d_name"),
        Python_h.C_POINTER.withName("d_qualname")
    ).withName("$anon$26:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout ob_base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ob_base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject ob_base
     * }
     */
    public static final GroupLayout ob_base$layout() {
        return ob_base$LAYOUT;
    }

    private static final long ob_base$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject ob_base
     * }
     */
    public static final long ob_base$offset() {
        return ob_base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject ob_base
     * }
     */
    public static MemorySegment ob_base(MemorySegment struct) {
        return struct.asSlice(ob_base$OFFSET, ob_base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject ob_base
     * }
     */
    public static void ob_base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ob_base$OFFSET, ob_base$LAYOUT.byteSize());
    }

    private static final AddressLayout d_type$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("d_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyTypeObject *d_type
     * }
     */
    public static final AddressLayout d_type$layout() {
        return d_type$LAYOUT;
    }

    private static final long d_type$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyTypeObject *d_type
     * }
     */
    public static final long d_type$offset() {
        return d_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyTypeObject *d_type
     * }
     */
    public static MemorySegment d_type(MemorySegment struct) {
        return struct.get(d_type$LAYOUT, d_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyTypeObject *d_type
     * }
     */
    public static void d_type(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(d_type$LAYOUT, d_type$OFFSET, fieldValue);
    }

    private static final AddressLayout d_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("d_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *d_name
     * }
     */
    public static final AddressLayout d_name$layout() {
        return d_name$LAYOUT;
    }

    private static final long d_name$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *d_name
     * }
     */
    public static final long d_name$offset() {
        return d_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *d_name
     * }
     */
    public static MemorySegment d_name(MemorySegment struct) {
        return struct.get(d_name$LAYOUT, d_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *d_name
     * }
     */
    public static void d_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(d_name$LAYOUT, d_name$OFFSET, fieldValue);
    }

    private static final AddressLayout d_qualname$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("d_qualname"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyObject *d_qualname
     * }
     */
    public static final AddressLayout d_qualname$layout() {
        return d_qualname$LAYOUT;
    }

    private static final long d_qualname$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyObject *d_qualname
     * }
     */
    public static final long d_qualname$offset() {
        return d_qualname$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyObject *d_qualname
     * }
     */
    public static MemorySegment d_qualname(MemorySegment struct) {
        return struct.get(d_qualname$LAYOUT, d_qualname$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyObject *d_qualname
     * }
     */
    public static void d_qualname(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(d_qualname$LAYOUT, d_qualname$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

