// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     PyDescrObject d_common;
 *     PyGetSetDef *d_getset;
 * }
 * }
 */
public class PyGetSetDescrObject {

    PyGetSetDescrObject() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        PyDescrObject.layout().withName("d_common"),
        Python_h.C_POINTER.withName("d_getset")
    ).withName("$anon$49:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout d_common$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("d_common"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyDescrObject d_common
     * }
     */
    public static final GroupLayout d_common$layout() {
        return d_common$LAYOUT;
    }

    private static final long d_common$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyDescrObject d_common
     * }
     */
    public static final long d_common$offset() {
        return d_common$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyDescrObject d_common
     * }
     */
    public static MemorySegment d_common(MemorySegment struct) {
        return struct.asSlice(d_common$OFFSET, d_common$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyDescrObject d_common
     * }
     */
    public static void d_common(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, d_common$OFFSET, d_common$LAYOUT.byteSize());
    }

    private static final AddressLayout d_getset$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("d_getset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyGetSetDef *d_getset
     * }
     */
    public static final AddressLayout d_getset$layout() {
        return d_getset$LAYOUT;
    }

    private static final long d_getset$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyGetSetDef *d_getset
     * }
     */
    public static final long d_getset$offset() {
        return d_getset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyGetSetDef *d_getset
     * }
     */
    public static MemorySegment d_getset(MemorySegment struct) {
        return struct.get(d_getset$LAYOUT, d_getset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyGetSetDef *d_getset
     * }
     */
    public static void d_getset(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(d_getset$LAYOUT, d_getset$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

