// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _heaptypeobject {
 *     PyTypeObject ht_type;
 *     PyAsyncMethods as_async;
 *     PyNumberMethods as_number;
 *     PyMappingMethods as_mapping;
 *     PySequenceMethods as_sequence;
 *     PyBufferProcs as_buffer;
 *     PyObject *ht_name;
 *     PyObject *ht_slots;
 *     PyObject *ht_qualname;
 *     struct _dictkeysobject *ht_cached_keys;
 *     PyObject *ht_module;
 *     char *_ht_tpname;
 *     struct _specialization_cache _spec_cache;
 * } PyHeapTypeObject
 * }
 */
public class PyHeapTypeObject extends _heaptypeobject {

    PyHeapTypeObject() {
        // Should not be called directly
    }
}

