// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     lenfunc mp_length;
 *     binaryfunc mp_subscript;
 *     objobjargproc mp_ass_subscript;
 * }
 * }
 */
public class PyMappingMethods {

    PyMappingMethods() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_POINTER.withName("mp_length"),
        Python_h.C_POINTER.withName("mp_subscript"),
        Python_h.C_POINTER.withName("mp_ass_subscript")
    ).withName("$anon$121:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout mp_length$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mp_length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * lenfunc mp_length
     * }
     */
    public static final AddressLayout mp_length$layout() {
        return mp_length$LAYOUT;
    }

    private static final long mp_length$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * lenfunc mp_length
     * }
     */
    public static final long mp_length$offset() {
        return mp_length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * lenfunc mp_length
     * }
     */
    public static MemorySegment mp_length(MemorySegment struct) {
        return struct.get(mp_length$LAYOUT, mp_length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * lenfunc mp_length
     * }
     */
    public static void mp_length(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mp_length$LAYOUT, mp_length$OFFSET, fieldValue);
    }

    private static final AddressLayout mp_subscript$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mp_subscript"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * binaryfunc mp_subscript
     * }
     */
    public static final AddressLayout mp_subscript$layout() {
        return mp_subscript$LAYOUT;
    }

    private static final long mp_subscript$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * binaryfunc mp_subscript
     * }
     */
    public static final long mp_subscript$offset() {
        return mp_subscript$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * binaryfunc mp_subscript
     * }
     */
    public static MemorySegment mp_subscript(MemorySegment struct) {
        return struct.get(mp_subscript$LAYOUT, mp_subscript$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * binaryfunc mp_subscript
     * }
     */
    public static void mp_subscript(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mp_subscript$LAYOUT, mp_subscript$OFFSET, fieldValue);
    }

    private static final AddressLayout mp_ass_subscript$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mp_ass_subscript"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * objobjargproc mp_ass_subscript
     * }
     */
    public static final AddressLayout mp_ass_subscript$layout() {
        return mp_ass_subscript$LAYOUT;
    }

    private static final long mp_ass_subscript$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * objobjargproc mp_ass_subscript
     * }
     */
    public static final long mp_ass_subscript$offset() {
        return mp_ass_subscript$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * objobjargproc mp_ass_subscript
     * }
     */
    public static MemorySegment mp_ass_subscript(MemorySegment struct) {
        return struct.get(mp_ass_subscript$LAYOUT, mp_ass_subscript$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * objobjargproc mp_ass_subscript
     * }
     */
    public static void mp_ass_subscript(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mp_ass_subscript$LAYOUT, mp_ass_subscript$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

