// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     PyDescrObject d_common;
 *     PyMethodDef *d_method;
 *     vectorcallfunc vectorcall;
 * }
 * }
 */
public class PyMethodDescrObject {

    PyMethodDescrObject() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        PyDescrObject.layout().withName("d_common"),
        Python_h.C_POINTER.withName("d_method"),
        Python_h.C_POINTER.withName("vectorcall")
    ).withName("$anon$38:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout d_common$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("d_common"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyDescrObject d_common
     * }
     */
    public static final GroupLayout d_common$layout() {
        return d_common$LAYOUT;
    }

    private static final long d_common$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyDescrObject d_common
     * }
     */
    public static final long d_common$offset() {
        return d_common$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyDescrObject d_common
     * }
     */
    public static MemorySegment d_common(MemorySegment struct) {
        return struct.asSlice(d_common$OFFSET, d_common$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyDescrObject d_common
     * }
     */
    public static void d_common(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, d_common$OFFSET, d_common$LAYOUT.byteSize());
    }

    private static final AddressLayout d_method$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("d_method"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyMethodDef *d_method
     * }
     */
    public static final AddressLayout d_method$layout() {
        return d_method$LAYOUT;
    }

    private static final long d_method$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyMethodDef *d_method
     * }
     */
    public static final long d_method$offset() {
        return d_method$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyMethodDef *d_method
     * }
     */
    public static MemorySegment d_method(MemorySegment struct) {
        return struct.get(d_method$LAYOUT, d_method$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyMethodDef *d_method
     * }
     */
    public static void d_method(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(d_method$LAYOUT, d_method$OFFSET, fieldValue);
    }

    private static final AddressLayout vectorcall$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("vectorcall"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * vectorcallfunc vectorcall
     * }
     */
    public static final AddressLayout vectorcall$layout() {
        return vectorcall$LAYOUT;
    }

    private static final long vectorcall$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * vectorcallfunc vectorcall
     * }
     */
    public static final long vectorcall$offset() {
        return vectorcall$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * vectorcallfunc vectorcall
     * }
     */
    public static MemorySegment vectorcall(MemorySegment struct) {
        return struct.get(vectorcall$LAYOUT, vectorcall$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * vectorcallfunc vectorcall
     * }
     */
    public static void vectorcall(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(vectorcall$LAYOUT, vectorcall$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

