// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     int slot;
 *     void *pfunc;
 * }
 * }
 */
public class PyType_Slot {

    PyType_Slot() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Python_h.C_INT.withName("slot"),
        MemoryLayout.paddingLayout(4),
        Python_h.C_POINTER.withName("pfunc")
    ).withName("$anon$499:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt slot$LAYOUT = (OfInt)$LAYOUT.select(groupElement("slot"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int slot
     * }
     */
    public static final OfInt slot$layout() {
        return slot$LAYOUT;
    }

    private static final long slot$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int slot
     * }
     */
    public static final long slot$offset() {
        return slot$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int slot
     * }
     */
    public static int slot(MemorySegment struct) {
        return struct.get(slot$LAYOUT, slot$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int slot
     * }
     */
    public static void slot(MemorySegment struct, int fieldValue) {
        struct.set(slot$LAYOUT, slot$OFFSET, fieldValue);
    }

    private static final AddressLayout pfunc$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pfunc"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *pfunc
     * }
     */
    public static final AddressLayout pfunc$layout() {
        return pfunc$LAYOUT;
    }

    private static final long pfunc$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *pfunc
     * }
     */
    public static final long pfunc$offset() {
        return pfunc$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *pfunc
     * }
     */
    public static MemorySegment pfunc(MemorySegment struct) {
        return struct.get(pfunc$LAYOUT, pfunc$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *pfunc
     * }
     */
    public static void pfunc(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(pfunc$LAYOUT, pfunc$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

